steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'alpha'
  - 'functions'
  - 'deploy'
  - 'create-cloud-tasks'
  - '--gen2'
  - '--region'
  - 'europe-west2'
  - '--runtime'
  - 'python38'
  - '--source'
  - '5_parallel_execution/fn_create_cloud_tasks'
  - '--entry-point'
  - 'generate_tasks'
  - '--trigger-http'
  - '--max-instances'
  - '5'
  - '--service-account'
  - '${_SERVICE_ACCOUNT}'
  - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY